//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace babgvant.EVRPlay {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PlaySettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PlaySettings defaultInstance = ((PlaySettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PlaySettings())));
        
        public static PlaySettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int SkipForward1 {
            get {
                return ((int)(this["SkipForward1"]));
            }
            set {
                this["SkipForward1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int SkipBack1 {
            get {
                return ((int)(this["SkipBack1"]));
            }
            set {
                this["SkipBack1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int SkipForward2 {
            get {
                return ((int)(this["SkipForward2"]));
            }
            set {
                this["SkipForward2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int SkipBack2 {
            get {
                return ((int)(this["SkipBack2"]));
            }
            set {
                this["SkipBack2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public int MaxInitialHeight {
            get {
                return ((int)(this["MaxInitialHeight"]));
            }
            set {
                this["MaxInitialHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("720")]
        public int MaxInitialWidth {
            get {
                return ((int)(this["MaxInitialWidth"]));
            }
            set {
                this["MaxInitialWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WriteLog {
            get {
                return ((bool)(this["WriteLog"]));
            }
            set {
                this["WriteLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int VideoAspectRatioMode {
            get {
                return ((int)(this["VideoAspectRatioMode"]));
            }
            set {
                this["VideoAspectRatioMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int VideoRenderingPrefs {
            get {
                return ((int)(this["VideoRenderingPrefs"]));
            }
            set {
                this["VideoRenderingPrefs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BorderColor {
            get {
                return ((int)(this["BorderColor"]));
            }
            set {
                this["BorderColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string VideoProcessorMode {
            get {
                return ((string)(this["VideoProcessorMode"]));
            }
            set {
                this["VideoProcessorMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FSControlTimeout {
            get {
                return ((int)(this["FSControlTimeout"]));
            }
            set {
                this["FSControlTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int MouseSensitivity {
            get {
                return ((int)(this["MouseSensitivity"]));
            }
            set {
                this["MouseSensitivity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.ts;{564FD788-86C9-4444-971E-CC4A243DA150};ffdshow Video Decoder</string>
  <string>.ts;Haali Media Splitter;CyberLink Demux (PDVD7)</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection BlockedFilters {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["BlockedFilters"]));
            }
            set {
                this["BlockedFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>.wmv;WMAudio Decoder DMO</string>
  <string>.ts;ArcSoft Video Decoder;{D5F9370B-E232-464F-BE29-A885B1249190}</string>
  <string>.ifo;Microsoft MPEG-2 Video Decoder</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection PreferredDecoders {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["PreferredDecoders"]));
            }
            set {
                this["PreferredDecoders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BookmarkDir {
            get {
                return ((string)(this["BookmarkDir"]));
            }
            set {
                this["BookmarkDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>E:\\Sage TV\\;\\\\sageserver\\Sage TV\\</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ReplacePaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ReplacePaths"]));
            }
            set {
                this["ReplacePaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PublishGraph {
            get {
                return ((bool)(this["PublishGraph"]));
            }
            set {
                this["PublishGraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int FileHistory {
            get {
                return ((int)(this["FileHistory"]));
            }
            set {
                this["FileHistory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SingleInstance {
            get {
                return ((bool)(this["SingleInstance"]));
            }
            set {
                this["SingleInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverscanWidth {
            get {
                return ((int)(this["OverscanWidth"]));
            }
            set {
                this["OverscanWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OverscanHeight {
            get {
                return ((int)(this["OverscanHeight"]));
            }
            set {
                this["OverscanHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost:8080/sage/home")]
        public string SageWebserver {
            get {
                return ((string)(this["SageWebserver"]));
            }
            set {
                this["SageWebserver"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sage")]
        public string SWUsername {
            get {
                return ((string)(this["SWUsername"]));
            }
            set {
                this["SWUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("frey")]
        public string SWPassword {
            get {
                return ((string)(this["SWPassword"]));
            }
            set {
                this["SWPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BrowseOnLoad {
            get {
                return ((bool)(this["BrowseOnLoad"]));
            }
            set {
                this["BrowseOnLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WOLMac {
            get {
                return ((string)(this["WOLMac"]));
            }
            set {
                this["WOLMac"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int BrowseAttempts {
            get {
                return ((int)(this["BrowseAttempts"]));
            }
            set {
                this["BrowseAttempts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool NeedsUpgrade {
            get {
                return ((bool)(this["NeedsUpgrade"]));
            }
            set {
                this["NeedsUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float Zoom {
            get {
                return ((float)(this["Zoom"]));
            }
            set {
                this["Zoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public float ZoomIncrement {
            get {
                return ((float)(this["ZoomIncrement"]));
            }
            set {
                this["ZoomIncrement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/sagepublic/PlaylistGenerator?Command=generate&pltype=pls&fntype=filepath&MediaFi" +
            "leId=$1")]
        public string MediaLaunch {
            get {
                return ((string)(this["MediaLaunch"]));
            }
            set {
                this["MediaLaunch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/Recordings?xml=yes")]
        public string SageRecording {
            get {
                return ((string)(this["SageRecording"]));
            }
            set {
                this["SageRecording"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"/Search?SearchString=&searchType=MediaFiles&Video=on&DVD=on&search_fields=title&filename=.*&regex=on&TimeRange=0&Categories=**Any**&Channels=**Any**&watched=any&dontlike=any&favorite=any&firstruns=any&hdtv=any&archived=any&manrec=any&autodelete=any&partials=none&sort1=title_asc&sort2=none&grouping=None&xml=yes")]
        public string SageMedia {
            get {
                return ((string)(this["SageMedia"]));
            }
            set {
                this["SageMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int CacheRecording {
            get {
                return ((int)(this["CacheRecording"]));
            }
            set {
                this["CacheRecording"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CacheMedia {
            get {
                return ((int)(this["CacheMedia"]));
            }
            set {
                this["CacheMedia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int MBButtonWidth {
            get {
                return ((int)(this["MBButtonWidth"]));
            }
            set {
                this["MBButtonWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150")]
        public int MBButtonHeight {
            get {
                return ((int)(this["MBButtonHeight"]));
            }
            set {
                this["MBButtonHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool OpenMediaBrowser {
            get {
                return ((bool)(this["OpenMediaBrowser"]));
            }
            set {
                this["OpenMediaBrowser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int PageSize {
            get {
                return ((int)(this["PageSize"]));
            }
            set {
                this["PageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseDtbXml {
            get {
                return ((bool)(this["UseDtbXml"]));
            }
            set {
                this["UseDtbXml"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PriorityClass {
            get {
                return ((int)(this["PriorityClass"]));
            }
            set {
                this["PriorityClass"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DtbXmlPath {
            get {
                return ((string)(this["DtbXmlPath"]));
            }
            set {
                this["DtbXmlPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MultiChannelWMA {
            get {
                return ((bool)(this["MultiChannelWMA"]));
            }
            set {
                this["MultiChannelWMA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DXVAWMV {
            get {
                return ((bool)(this["DXVAWMV"]));
            }
            set {
                this["DXVAWMV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5325DF1C-6F10-4292-B8FB-BE855F99F88A")]
        public string CustomPresenter {
            get {
                return ((string)(this["CustomPresenter"]));
            }
            set {
                this["CustomPresenter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CustomPresenterEnabled {
            get {
                return ((bool)(this["CustomPresenterEnabled"]));
            }
            set {
                this["CustomPresenterEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{EC9ED6FC-7B03-4CB6-8C01-4EABE109F26B}")]
        public string CustomAudioRender {
            get {
                return ((string)(this["CustomAudioRender"]));
            }
            set {
                this["CustomAudioRender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseCustomAudioRenderer {
            get {
                return ((bool)(this["UseCustomAudioRenderer"]));
            }
            set {
                this["UseCustomAudioRenderer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AudioPlaybackDevice {
            get {
                return ((string)(this["AudioPlaybackDevice"]));
            }
            set {
                this["AudioPlaybackDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseBookmarks {
            get {
                return ((bool)(this["UseBookmarks"]));
            }
            set {
                this["UseBookmarks"] = value;
            }
        }
    }
}
